# Generated by Django 5.1.2 on 2024-10-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCourseQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('question', models.TextField(verbose_name='Question')),
                ('option1', models.CharField(max_length=255, verbose_name='Option 1')),
                ('option2', models.CharField(max_length=255, verbose_name='Option 2')),
                ('option3', models.CharField(max_length=255, verbose_name='Option 3')),
                ('option4', models.CharField(max_length=255, verbose_name='Option 4')),
                ('correct_option', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=10, verbose_name='Correct Option')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCourseQuizPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('points_title', models.CharField(max_length=50, verbose_name='Points Title')),
                ('points_value', models.IntegerField(verbose_name='Points Value')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCourseQuizSubmit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Score')),
            ],
        ),
    ]
