# Generated by Django 5.1.2 on 2024-10-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual_course_enrollment', '0001_initial'),
        ('individual_course_quizes', '0001_initial'),
        ('individual_course_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualcoursequiz',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_templates.individualcoursetemplate', verbose_name='Individual Course Template'),
        ),
        migrations.AddField(
            model_name='individualcoursequizpoints',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_quizes.individualcoursequiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='individualcoursequizsubmit',
            name='RA_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_enrollment.individualcourseenrolment', verbose_name='Individual Course Enrolment'),
        ),
        migrations.AddField(
            model_name='individualcoursequizsubmit',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_quizes.individualcoursequiz', verbose_name='Quiz'),
        ),
    ]
