# Generated by Django 5.1.2 on 2024-10-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_course_quizes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualcoursequizsubmit',
            old_name='RA_enrollment',
            new_name='individual_course_enrollment',
        ),
    ]
