# Generated by Django 5.1.2 on 2024-10-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual_course', '0001_initial'),
        ('individual_course_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCourseChapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('individual_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course.individualcourse', verbose_name='Individual Course')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCourseChapterComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateField(verbose_name='Created At')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_chapters.individualcoursechapter', verbose_name='Chapter')),
                ('individual_course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_enrollment.individualcourseenrolment')),
            ],
        ),
    ]
