# Generated by Django 5.1.2 on 2024-10-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_course_chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualcoursechapter',
            name='index',
            field=models.IntegerField(verbose_name='Index'),
        ),
    ]
