# Generated by Django 5.1.2 on 2024-10-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual_course', '0001_initial'),
        ('role_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCourseEnrolment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_course', models.BooleanField(verbose_name='Completed Course')),
                ('status', models.BooleanField(default=False, verbose_name='Enroll')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('expirate', models.BooleanField(default=False, verbose_name='Expirate')),
                ('individual_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course.individualcourse', verbose_name='Individual Course')),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role_management.roleassignment', verbose_name='Role Assignment')),
            ],
        ),
    ]
