# Generated by Django 5.1.2 on 2024-10-13 09:27

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=django_jalali.db.models.jDateField(verbose_name='Birth Date'),
        ),
    ]
