# Generated by Django 5.1.2 on 2024-10-13 09:48

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='Birth Date'),
        ),
    ]
