# Generated by Django 5.1.2 on 2024-10-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual_course_chapters', '0002_alter_individualcoursechapter_index'),
        ('individual_course_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCourseLessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('index', models.IntegerField(verbose_name='Index')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_chapters.individualcoursechapter', verbose_name='Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCourseLessonsComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateField(verbose_name='Created At')),
                ('individual_course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_enrollment.individualcourseenrolment')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_course_lessons.individualcourselessons', verbose_name='Lessons')),
            ],
        ),
    ]
