# Generated by Django 5.1.2 on 2024-10-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_course_enrollment', '0001_initial'),
        ('individual_course_short_quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndividualShorQuizOptions',
            new_name='IndividualShortQuizOptions',
        ),
        migrations.RenameModel(
            old_name='IndividualShorQuizPoints',
            new_name='IndividualShortQuizPoints',
        ),
        migrations.RenameModel(
            old_name='IndividualShorQuizSubmit',
            new_name='IndividualShortQuizSubmit',
        ),
    ]
