# Generated by Django 5.0.7 on 2024-10-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('enablecompletion', models.BooleanField(default=False)),
                ('completionnotify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_status', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_more_details',
            name='RA_id',
        ),
        migrations.RemoveField(
            model_name='teacher_more_details',
            name='RA_id',
        ),
        migrations.CreateModel(
            name='RALevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
                ('level_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.roleassignment')),
            ],
        ),
        migrations.CreateModel(
            name='studentMoreDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('home_number', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.roleassignment')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptonCoursePlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.course')),
                ('subscription_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionInPlanHisotry',
            fields=[
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='educationalapp.roleassignment')),
                ('payment_type', models.CharField(max_length=255)),
                ('payment_code', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField()),
                ('payment_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('subscription_course_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.subscriptoncourseplan')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionInPlan',
            fields=[
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='educationalapp.roleassignment')),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_code', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('payment_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('downgraded_at', models.DateTimeField(blank=True, null=True)),
                ('upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.subscriptiondiscount')),
                ('downgraded_to_plan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downgraded_plan', to='educationalapp.subscriptoncourseplan')),
                ('renewed_subscription_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewed_subscription', to='educationalapp.subscriptoncourseplan')),
                ('subscription_course_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.subscriptoncourseplan')),
                ('upgrade_to_plan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_plan', to='educationalapp.subscriptoncourseplan')),
            ],
        ),
        migrations.CreateModel(
            name='teacherMoreDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('expertise', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.roleassignment')),
            ],
        ),
        migrations.DeleteModel(
            name='RA_level',
        ),
        migrations.DeleteModel(
            name='student_more_details',
        ),
        migrations.DeleteModel(
            name='teacher_more_details',
        ),
    ]
