# Generated by Django 5.0.7 on 2024-10-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0002_course_subscriptiondiscount_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninplan',
            name='RA_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='educationalapp.roleassignment'),
        ),
        migrations.AlterField(
            model_name='subscriptioninplanhisotry',
            name='RA_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='educationalapp.roleassignment'),
        ),
    ]
