# Generated by Django 5.0.7 on 2024-10-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0003_alter_subscriptioninplan_ra_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseEnroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('enroll', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('enroll_period', models.IntegerField()),
                ('enroll_start_date', models.DateField()),
                ('enroll_end_date', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('expire_notify', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.roleassignment')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='RAEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('time_expiration', models.DateTimeField(auto_now=True)),
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.roleassignment')),
                ('course_enroll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.courseenroll')),
            ],
        ),
    ]
