# Generated by Django 5.0.7 on 2024-10-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0004_courseenroll_raenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='automaticCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('prerequisite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='educationalapp.automaticcourse')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('edit_date', models.DateField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('language', models.CharField(max_length=10)),
                ('enable_completion', models.BooleanField(default=False)),
                ('completion_notify', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('enable_completion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourse')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseFaze',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('sub_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faze_intro_title', models.CharField(max_length=255)),
                ('faze_intro_content', models.TextField()),
                ('faze_review_title', models.CharField(max_length=255)),
                ('faze_review_content', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourse')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseFazeComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('faze_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefaze')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseFazeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('faze_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefaze')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseFazeGroupSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(max_length=50)),
                ('n_the_section', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('faze_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroup')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseFazeGroupComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('faze_group_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroupsection')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseFazeGroupSectionContentTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('section_content', models.TextField()),
                ('has_next_btn', models.BooleanField(default=False)),
                ('faze_group_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroupsection')),
            ],
        ),
        migrations.AddField(
            model_name='automaticcourse',
            name='course_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursegroup'),
        ),
        migrations.CreateModel(
            name='automaticCourseGroupComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('course_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='columnType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('question', 'Question'), ('content', 'Number'), ('data', 'Data')], max_length=50)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroupsectioncontenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='templateQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct_option', models.CharField(max_length=255)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroupsectioncontenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='submitQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.templatequiz')),
            ],
        ),
        migrations.CreateModel(
            name='templateShorQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroupsectioncontenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='submitShortQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('short_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.templateshorquiz')),
            ],
        ),
        migrations.CreateModel(
            name='shortQuizOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('short_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.templateshorquiz')),
            ],
        ),
        migrations.CreateModel(
            name='quizPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_title', models.CharField(max_length=255)),
                ('points_value', models.IntegerField()),
                ('short_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.templateshorquiz')),
            ],
        ),
    ]
