# Generated by Django 5.0.7 on 2024-10-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0005_automaticcourse_automaticcoursegroup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='meetBasedCourse',
        ),
        migrations.RemoveField(
            model_name='raenrollment',
            name='course_enroll_id',
        ),
        migrations.RemoveField(
            model_name='subscriptoncourseplan',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subscriptoncourseplan',
            name='subscription_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscriptioninplanhisotry',
            name='subscription_course_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscriptioninplan',
            name='subscription_course_plan_id',
        ),
        migrations.RenameField(
            model_name='automaticcoursecomplete',
            old_name='course_id',
            new_name='automatic_course_id',
        ),
        migrations.RenameField(
            model_name='automaticcoursefaze',
            old_name='course_id',
            new_name='automatic_course_id',
        ),
        migrations.RemoveField(
            model_name='automaticcoursefazegroupcomplete',
            name='faze_group_section_id',
        ),
        migrations.RemoveField(
            model_name='quizpoints',
            name='short_quiz_id',
        ),
        migrations.AddField(
            model_name='automaticcoursefazegroupcomplete',
            name='faze_group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroup'),
        ),
        migrations.AddField(
            model_name='quizpoints',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.templatequiz'),
        ),
        migrations.AlterField(
            model_name='automaticcoursefazegroupsection',
            name='faze_group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroup'),
        ),
        migrations.CreateModel(
            name='automaticCourseEnroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('enroll', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('enroll_period', models.IntegerField()),
                ('enroll_start_date', models.DateField()),
                ('enroll_end_date', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('expire_notify', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('RA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.roleassignment')),
                ('automatic_course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourse')),
            ],
        ),
        migrations.AddField(
            model_name='raenrollment',
            name='automatic_course_enroll_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourseenroll'),
        ),
        migrations.CreateModel(
            name='automaticCourseFazeGroupsectionComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_modified', models.DateField()),
                ('RA_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.raenrollment')),
                ('faze_group_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcoursefazegroupsection')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCoursePlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('automatic_course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourse')),
                ('subscription_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptioninplan',
            name='automatic_course_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourseplan'),
        ),
        migrations.AddField(
            model_name='subscriptioninplanhisotry',
            name='automatic_course_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educationalapp.automaticcourseplan'),
        ),
        migrations.AlterField(
            model_name='subscriptioninplan',
            name='downgraded_to_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downgraded_plan', to='educationalapp.automaticcourseplan'),
        ),
        migrations.AlterField(
            model_name='subscriptioninplan',
            name='renewed_subscription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewed_subscription', to='educationalapp.automaticcourseplan'),
        ),
        migrations.AlterField(
            model_name='subscriptioninplan',
            name='upgrade_to_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_plan', to='educationalapp.automaticcourseplan'),
        ),
        migrations.CreateModel(
            name='shortQuizPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_title', models.CharField(max_length=255)),
                ('points_value', models.IntegerField()),
                ('short_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.templateshorquiz')),
            ],
        ),
        migrations.DeleteModel(
            name='courseEnroll',
        ),
        migrations.DeleteModel(
            name='subscriptonCoursePlan',
        ),
    ]
