# Generated by Django 5.0.7 on 2024-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0006_rename_course_meetbasedcourse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscriptionInPlan',
            new_name='automaticCourseSubscriptionInPlan',
        ),
        migrations.RenameModel(
            old_name='RAEnrollment',
            new_name='automaticRAEnrollment',
        ),
        migrations.AddField(
            model_name='submitquiz',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='submitshortquiz',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
