# Generated by Django 5.0.7 on 2024-10-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapp', '0007_rename_subscriptioninplan_automaticcoursesubscriptioninplan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscriptionInPlanHisotry',
            new_name='automaticCourseSubscriptionInPlanHisotry',
        ),
        migrations.CreateModel(
            name='automaticCourseStrike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strike_start_date', models.DateField()),
                ('strike_day_name', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('battery_status_number', models.SmallIntegerField()),
                ('battery_status', models.CharField(choices=[('one', 'One'), ('two', 'Two')], max_length=50)),
                ('strike_length', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('strike_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='automaticCourseStrikeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strike_start_date', models.DateField()),
                ('strike_day_name', models.CharField(max_length=10)),
                ('battery_status', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educationalapp.user')),
            ],
        ),
    ]
