# Generated by Django 5.1.2 on 2024-10-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCourseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Edit Date')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('enable_completed', models.BooleanField(default=False, verbose_name='Enable Completed')),
            ],
        ),
    ]
